/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as WWorkspaceCodeRouteRouteImport } from './routes/w/$workspaceCode/route'
import { Route as WWorkspaceCodeIndexRouteImport } from './routes/w/$workspaceCode/index'
import { Route as WWorkspaceCodeSpaceCodeIndexRouteImport } from './routes/w/$workspaceCode/$spaceCode/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const WWorkspaceCodeRouteRoute = WWorkspaceCodeRouteRouteImport.update({
  id: '/w/$workspaceCode',
  path: '/w/$workspaceCode',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceCodeIndexRoute = WWorkspaceCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceCodeRouteRoute,
} as any)
const WWorkspaceCodeSpaceCodeIndexRoute =
  WWorkspaceCodeSpaceCodeIndexRouteImport.update({
    id: '/$spaceCode/',
    path: '/$spaceCode/',
    getParentRoute: () => WWorkspaceCodeRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/w/$workspaceCode': typeof WWorkspaceCodeRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/w/$workspaceCode/': typeof WWorkspaceCodeIndexRoute
  '/w/$workspaceCode/$spaceCode/': typeof WWorkspaceCodeSpaceCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/w/$workspaceCode': typeof WWorkspaceCodeIndexRoute
  '/w/$workspaceCode/$spaceCode': typeof WWorkspaceCodeSpaceCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/w/$workspaceCode': typeof WWorkspaceCodeRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/w/$workspaceCode/': typeof WWorkspaceCodeIndexRoute
  '/w/$workspaceCode/$spaceCode/': typeof WWorkspaceCodeSpaceCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/w/$workspaceCode'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/'
    | '/w/$workspaceCode/'
    | '/w/$workspaceCode/$spaceCode/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth'
    | '/w/$workspaceCode'
    | '/w/$workspaceCode/$spaceCode'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/w/$workspaceCode'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/'
    | '/w/$workspaceCode/'
    | '/w/$workspaceCode/$spaceCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  WWorkspaceCodeRouteRoute: typeof WWorkspaceCodeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/w/$workspaceCode': {
      id: '/w/$workspaceCode'
      path: '/w/$workspaceCode'
      fullPath: '/w/$workspaceCode'
      preLoaderRoute: typeof WWorkspaceCodeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceCode/': {
      id: '/w/$workspaceCode/'
      path: '/'
      fullPath: '/w/$workspaceCode/'
      preLoaderRoute: typeof WWorkspaceCodeIndexRouteImport
      parentRoute: typeof WWorkspaceCodeRouteRoute
    }
    '/w/$workspaceCode/$spaceCode/': {
      id: '/w/$workspaceCode/$spaceCode/'
      path: '/$spaceCode'
      fullPath: '/w/$workspaceCode/$spaceCode/'
      preLoaderRoute: typeof WWorkspaceCodeSpaceCodeIndexRouteImport
      parentRoute: typeof WWorkspaceCodeRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface WWorkspaceCodeRouteRouteChildren {
  WWorkspaceCodeIndexRoute: typeof WWorkspaceCodeIndexRoute
  WWorkspaceCodeSpaceCodeIndexRoute: typeof WWorkspaceCodeSpaceCodeIndexRoute
}

const WWorkspaceCodeRouteRouteChildren: WWorkspaceCodeRouteRouteChildren = {
  WWorkspaceCodeIndexRoute: WWorkspaceCodeIndexRoute,
  WWorkspaceCodeSpaceCodeIndexRoute: WWorkspaceCodeSpaceCodeIndexRoute,
}

const WWorkspaceCodeRouteRouteWithChildren =
  WWorkspaceCodeRouteRoute._addFileChildren(WWorkspaceCodeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  WWorkspaceCodeRouteRoute: WWorkspaceCodeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
